core:
  tip_radius_um: 5.0
  k_frame_z: 750000.0
  k_frame_x: 128200.0
  pattern: "*.csv"
  outdir: "results"
  k_sup_x_fallback: 250.0 # N/m
  c_sup_x_fallback: 0.11 # Ns/m
  allow_no_cal: True
  dyn_f2_freq_Hz: 10.    # lateral CSM frequency

touch:
  k_touch_min: 650. ## critical for touch detection -tune up if touch mistaken by noise
  k_touch_min_duration_s: 0.1
  loading_rate_threshold: 0.02 ## critial for touch detection -tune up if touch mistaken by noise
  normal_load_sustain: 2 # seconds at steady -below threshold loading rate
  normal_load_smooth: 301;

cycles:
  smooth_n: 51
  dynF2_baseline_q: 0.02
  dynF2_active_delta: 0.0001 # increase it for low load/noisy-mN
  dynF2_nearzero_delta: 0.0001 #critical for cycle detection -thershold of lateral dyn force-mN
  hold_top_frac: 0.98
  hold_min_s: 0.2
  min_cycle_points: 200
  dfdt_smooth_n: 101
  dfdt_thr_frac: 0.0001 ## if noisy or low load experiment-> increase
  dfdt_hold_frac: 0.9
  min_ramp_s: 12.0 ## to separate easily from initial loading dyn. lateral force
  min_hold_s: 0.5
  expected_cycles: 3

transition:
  trans_frac_up: 0.15
  trans_frac_down: 0.15
  sliding_lateral_stiffness_thresh: 500.
  resticking_lateral_stiffness_thresh: 1000.
  trans_low_band: [0.005, 0.1]
  trans_smooth_n: 301
  trans_mode: "phase"
  trans_min_valid_Ft_frac: 0.003
  trans_skip_start_frac_up: 0.012  
  trans_skip_end_frac_dn: 0.01
  phase_near_max_frac: 0.98

hertz:
  hertz_enable: true
  hardness_Pa: 1.0e10
  plasticity_p0_frac: 1.0
  hertz_min_h_m: 2.0e-10
  hertz_max_frac_of_Pmax: 1.0
  hertz_min_points: 50
  hertz_iter: 10
  hertz_plot: true
  area_mode: "nominal_stiffness"

materials:
  E1_GPa: 72.
  nu1: 0.2
  E2_GPa: 1140.0
  nu2: 0.07

adhesion:
  adhesion_model: "auto"
  w_J_per_m2: 0.5
  sigma_rms_m: 0.5e-9
  rough_model: "exp"
  delta0_m: 0.3e-9
  z0_m: 0.3e-9
  mu_dmt: 1.0
  mu_jkr: 5.0
  min_h_m: 1.0e-10
  max_frac_of_Pmax: 1.0
  min_points: 150
  n_iter: 10

plotting:
  manual_mode: "always"
  manual_cycle_mode: "always"
  plot_mindlin: true
  plot_cycles: true
  live_plots: true
  plot_every: 1
  summary_plots: true
  origin_csv: true
  summary_template: true
